# Generated by Django 3.0.4 on 2020-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('des', models.CharField(default='', max_length=50)),
                ('icon', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
