# Generated by Django 3.0.4 on 2020-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
